In [5]:
ak.stock_zh_a_hist(symbol='000001',period="daily", start_date="20100101", end_date='20231231', adjust="hfq")

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2010-01-04,1402.93,1355.31,1406.45,1353.55,241923,5.802495e+08,3.79,-2.78,-38.80,0.83
1,2010-01-05,1357.66,1331.21,1366.48,1298.88,556500,1.293477e+09,4.99,-1.78,-24.10,1.90
2,2010-01-06,1328.27,1307.70,1328.27,1297.12,412143,9.444537e+08,2.34,-1.77,-23.51,1.41
3,2010-01-07,1307.70,1293.00,1316.51,1278.30,355337,8.041663e+08,2.92,-1.12,-14.70,1.22
4,2010-01-08,1284.18,1290.06,1298.88,1275.37,288543,6.506674e+08,1.82,-0.23,-2.94,0.99
...,...,...,...,...,...,...,...,...,...,...,...
3326,2023-12-25,1744.23,1745.85,1747.48,1737.73,413971,3.796382e+08,0.56,-0.09,-1.63,0.21
3327,2023-12-26,1745.85,1731.22,1747.48,1726.35,541896,4.937466e+08,1.21,-0.84,-14.63,0.28
3328,2023-12-27,1731.22,1734.48,1736.10,1718.22,641534,5.820367e+08,1.03,0.19,3.26,0.33
3329,2023-12-28,1732.85,1788.11,1791.36,1727.97,1661592,1.550257e+09,3.65,3.09,53.63,0.86
3330,2023-12-29,1783.23,1778.36,1792.99,1771.86,853853,8.031967e+08,1.18,-0.55,-9.75,0.44

In [1]:
import akshare as ak
import pandas as pd
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")

def get_stock_data(column_name='收盘'):
    # 获取所有A股股票代码列表
    stock_list = ak.stock_zh_a_spot_em()['代码'].tolist()

    # 初始化一个空的DataFrame来存储所有股票的数据
    all_stocks = pd.DataFrame(index=ak.stock_zh_a_hist(symbol='000001',period="daily", start_date="20100101", end_date='20231231', adjust="hfq")['日期'])

    # 使用 tqdm 创建一个进度条
    for code in tqdm(stock_list, desc='Downloading'):
        try:
            # 获取单只股票的历史数据
            stock_data = ak.stock_zh_a_hist(symbol=code,period="daily", start_date="20100101", end_date='20231231', adjust="hfq")

            # 检查所需的列是否在数据中
            if column_name in stock_data.columns:
                # 将选定的列添加到大的DataFrame中
                all_stocks[code] = stock_data.set_index('日期')[column_name]
        except Exception as e:
            print(f"Error fetching data for stock: {code}, error: {e}")
            continue

    return all_stocks

# 使用函数
stock_close_prices = get_stock_data('收盘')
stock_close_prices.index = pd.to_datetime(stock_close_prices.index)

C:\Users\MSI-Gaming\anaconda3\lib\site-packages\akshare\__init__.py:2670: UserWarning: 为了支持更多特性，请将 Pandas 升级到 2.1.0 及以上版本！
  warnings.warn(
Downloading: 100%|█████████████████████████████████████████████████████████████████| 5587/5587 [07:19<00:00, 12.72it/s]

In [2]:
stock_close_prices

,873122,872541,300096,300374,301001,301315,300899,301058,300175,837174,...,001217,870726,688503,002042,301302,600156,003027,603688,001216,300982
日期,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.80,NaN,6.90,NaN,NaN,NaN,NaN
2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.82,NaN,7.00,NaN,NaN,NaN,NaN
2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.78,NaN,6.96,NaN,NaN,NaN,NaN
2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.16,NaN,6.63,NaN,NaN,NaN,NaN
2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.09,NaN,6.72,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-25,29.34,13.30,34.08,24.25,25.35,50.92,27.12,11.20,24.90,61.88,...,11.62,21.87,76.03,25.18,36.74,5.44,27.28,125.87,12.86,37.34
2023-12-26,32.63,13.36,33.08,24.02,24.37,49.60,26.90,11.11,24.90,63.08,...,11.64,21.92,74.70,24.82,35.21,5.31,27.19,124.92,12.77,36.39
2023-12-27,30.93,13.21,34.48,24.33,24.48,50.67,27.18,11.14,25.61,63.40,...,12.07,22.67,75.10,25.36,34.80,5.32,27.29,126.56,12.95,36.21
2023-12-28,30.08,13.26,35.08,25.47,24.79,52.62,27.54,11.27,25.04,63.64,...,13.24,23.45,81.52,25.54,35.34,5.26,28.30,136.22,13.14,38.67
2023-12-29,30.11,13.99,NaN,25.71,25.79,52.86,28.04,11.28,26.80,64.08,...,14.52,23.72,79.87,25.81,37.67,5.52,28.72,135.47,13.47,40.86

In [4]:
stock_close_prices.to_hdf('close.h5', key='data')

In [6]:
stock_open_prices = get_stock_data('开盘')
stock_open_prices.index = pd.to_datetime(stock_open_prices.index)
stock_open_prices.to_hdf('open.h5', key='data')

Downloading: 100%|█████████████████████████████████████████████████████████████████| 5587/5587 [07:00<00:00, 13.28it/s]

In [7]:
stock_volume = get_stock_data('成交量')
stock_volume.index = pd.to_datetime(stock_volume.index)
stock_volume.to_hdf('volume.h5', key='data')

Downloading: 100%|█████████████████████████████████████████████████████████████████| 5587/5587 [07:24<00:00, 12.56it/s]

In [8]:
stock_high = get_stock_data('最高')
stock_high.index = pd.to_datetime(stock_high.index)
stock_high.to_hdf('high.h5', key='data')

Downloading: 100%|█████████████████████████████████████████████████████████████████| 5587/5587 [07:30<00:00, 12.40it/s]

In [9]:
stock_low = get_stock_data('最低')
stock_low.index = pd.to_datetime(stock_low.index)
stock_low.to_hdf('low.h5', key='data')

Downloading: 100%|█████████████████████████████████████████████████████████████████| 5587/5587 [06:57<00:00, 13.37it/s]